spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/rogerLeican/config-repo

server:
  port: 8888
  servlet:
    context-path: /config-server

